# Generated by Django 4.0.4 on 2022-05-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='img',
            field=models.ImageField(upload_to='media/%Y/%m/%d'),
        ),
    ]
