# Generated by Django 4.0.4 on 2022-05-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_produto_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='pais',
            field=models.CharField(choices=[('Br', 'Brasil'), ('ES', 'Internacional')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
