# Generated by Django 4.0.4 on 2022-06-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='pais',
            field=models.CharField(choices=[('br', 'Brasil'), ('es', 'Internacional')], max_length=2),
        ),
    ]
